api_platform:
    title: Hello API Platform
    version: 1.0.0
    use_symfony_listeners: true
    # Désactive complètement l'intégration Doctrine ORM
    doctrine: false

    # Configure pour utiliser MongoDB ODM uniquement
    doctrine_mongodb_odm:
        enabled: true
    formats:
        jsonld: ["application/ld+json"]
        multipart: ["multipart/form-data"]
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
