api_platform:
    title: Hello API Platform
    version: 1.0.0
    use_symfony_listeners: true
    formats:
        jsonld: ["application/ld+json"]
        multipart: ["multipart/form-data"]
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
