vich_uploader:
    db_driver: mongodb
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: "%kernel.project_dir%/public/uploads/lessons"
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
