version: "3.8"

services:
    app_test_acadyo:
        build:
            context: .
            args:
                APP_ENV: test
        environment:
            - MONGODB_URL=mongodb://root:rootpassword@db_acadyo_test:27017/db_acadyo_test?authSource=admin
            - MONGODB_DB_TEST=db_acadyo_test
            - APP_ENV=test
            - MAILER_DSN=null://null
            - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
            - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
        depends_on:
            - db_acadyo_test
        networks:
            - test-network
        command: >
            sh -c "
                wait-for-it.sh db_acadyo_test:27017 --timeout=60 --strict -- echo 'MongoDB est prêt !'
                mkdir -p /var/www/html/var/cache /var/www/html/var/log \&& chown -R www-data:www-data /var/www/html \&& chmod -R 775 /var/www/html/var
                echo 'Chargement des fixtures de test...'
                php bin/console doctrine:mongodb:fixtures:load --no-interaction --env=test
                echo 'Lancement des tests...'
                php bin/phpunit
                echo 'Tests terminés'
            "

    db_acadyo_test:
        image: mongo:8.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            MONGO_INITDB_DATABASE: db_acadyo_test
        networks:
            - test-network
        tmpfs:
            - /data/db # Utilise la RAM pour la base de test (plus rapide)

networks:
    test-network:
        driver: bridge
