version: "3.8"

services:
    # Service de l'application Symfony
    app_acadyo:
        build:
            context: .
            args:
                APP_ENV: ${APP_ENV}
        environment:
            - MONGODB_URL=mongodb://briandev:0000@31.97.192.58/acadyo?authSource=acadyo
            - APP_ENV=${APP_ENV}
            - CORS_ALLOW_ORIGIN=http://acadyo.briancoupama.re
            - ADMIN_NAME=${ADMIN_NAME}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        ports:
            - "8000:80"
        # Suppression de depends_on car plus de container MongoDB local
        networks:
            - npm-network
        command: ["sh", "/var/www/html/docker/entrypoint.sh"]
        volumes:
            - symfony_var:/var/www/html/var

    # Optionnel: Mongo Express pour votre MongoDB distant
    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: briandev
            ME_CONFIG_MONGODB_ADMINPASSWORD: "0000"
            ME_CONFIG_MONGODB_URL: mongodb://briandev:0000@31.97.192.58/acadyo?authSource=acadyo
            ME_CONFIG_BASICAUTH: false
        ports:
            - "8081:8081"
        networks:
            - npm-network

volumes:
    symfony_var:

networks:
    npm-network:
        external: true
