version: "3.8"

services:
    app_test_acadyo:
        build:
            context: .
            args:
                APP_ENV: test
        environment:
            - MONGODB_URL=mongodb://root:rootpassword@db_acadyo_test:27017/db_acadyo_test?authSource=admin
            - MONGODB_DB_TEST=db_acadyo_test
            - APP_ENV=test
            - MAILER_DSN=null://null
            - CLOUDINARY_CLOUD_NAME=duouyfqku
            - CLOUDINARY_API_KEY=279999917813899
            - CLOUDINARY_API_SECRET=KCkgOO9NTN_95opTHz9lXYktlvg
        depends_on:
            - db_acadyo_test
        networks:
            - test-network

    db_acadyo_test:
        image: mongo:8.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            MONGO_INITDB_DATABASE: db_acadyo_test
        networks:
            - test-network
        tmpfs:
            - /data/db # Utilise la RAM pour la base de test (plus rapide)

networks:
    test-network:
        driver: bridge
