# config/services_test.yaml
services:
    _defaults:
        public: true

    App\Service\CloudinaryService:
        public: true
    # Si vous voulez un mock par défaut pour tous les tests
    test.cloudinary_service:
        class: App\Service\CloudinaryService
        public: true
        # Mock par défaut qui ne fait rien
